### ISSUE TITLE
Bump unicase dependency

### ISSUE THREAD

**Issue by kpcyrd** [abonander/mime_guess#37]
mime_guess currently depends on unicase 0.1, please consider bumping to unicase 0.2 :)

Thanks!

**Comment by abonander** [comment]
This isn't completely trivial because at some point either unicase dropped support for phf or vice versa. Upgrading one or both dependencies would require new adapter types to be written so `UniCase` can again be used to index into a `phf::OrderedMap`.

**Comment by nox** [comment]
Would you accept a patch doing that?

**Comment by abonander** [comment]
Absolutely. The other issue now is that `UniCase` no longer provides a const constructor but the adapter type can work around that.

**Comment by abonander** [comment]
I've submitted a PR to `unicase`, linked above. Using `const fn` would require a bump of the minimum Rust version to 1.31, I'm sure that's suitable for Servo though.

**Comment by abonander** [comment]
I have opened a PR fixing the blockers for upgrade: sfackler/rust-phf#152
