### ISSUE TITLE
feature: convenience method to get mime type from string

### ISSUE THREAD

**Issue by yoshuawuyts** [abonander/mime_guess#39]
It takes a bit of boilerplate to convert `/foo/img.png` to MIME `image/png`:
```rust
  pub fn get_mime(src: &str) -> String {
    let ext = Path::new(src)
      .extension()
      .and_then(OsStr::to_str)
      .unwrap_or("");
    let mime_type = mime_guess::get_mime_type(&ext);
    format!("{}/{}", mime_type.type_(), mime_type.subtype())
  }
```
It'd be nice if there was a convenience method built-in that would so something similar to the above.

Thanks!

**Comment by abonander** [comment]
I think #38 will cover this, I just keep forgetting to merge it.

**Comment by yoshuawuyts** [comment]
I figured it out:
```rust
    let icon_type = mime_guess::guess_mime_type(&src).to_string();
```

What tripped me up here is that `.to_string()` didn't show up in the docs at all, so I didn't know it was available. Thanks for the quick reply tho!

**Comment by abonander** [comment]
That's because `Mime` implements `Display` and `ToString` is implemented for all implementors of that.
