### ISSUE TITLE
mime_guess 2.0.0

### ISSUE THREAD

**Issue by ignatenkobrain** [abonander/mime_guess#42]
Hello folks,

I just realized that latest version of reqwest depends on beta version of mime_guess, would it be feasible to make a new release? In general we try to avoid packaging alpha/beta versions in Fedora.

Let me know your opinion and thanks in advance!

**Comment by abonander** [comment]
This is already being discussed in #26.

If `mime` is going to stabilize soon then I'd like to wait for that.
