### ISSUE TITLE
build error with 2.0.0

### ISSUE THREAD

**Issue by sallyyu0** [abonander/mime_guess#51]
I'm getting following error today from cargo test. My project does not use mime-guess directly, but some crates I used might have. Any clues?

Compiling mime_guess v2.0.0
Compiling mime v0.3.13
error[E0658]: renaming imports with _ is unstable (see issue #48216)
--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/mime_guess-2.0.0/build.rs:120:9
|
120 | use std::fmt::Write as _;
| ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try rustc --explain E0658.
error: Could not compile mime_guess.
warning: build failed, waiting for other jobs to finish...
error: build failed

Note: it was ok when for mime_guess v2.0.0-alpha.6. Someone suggested it's caused by old compiler. What's the requirement change on the new release v2.0.0?

**Comment by abonander** [comment]
That feature was stabilized in 1.33.0. Even Ubuntu LTS has Rust newer than that now. Unless you're stuck on Debian Jessie/Stretch I'd recommend updating.
