### ISSUE TITLE
Add mime types for `.eot`, `.woff`, and `.ttf`

### ISSUE THREAD

**Issue by jyn514** [abonander/mime_guess#63]
https://github.com/rust-lang/docs.rs/pull/981/files/30ae9067caf59b1dc96925fcd6400e0eace73cc3..b38d996173daa8fb2a9819015e939c6947acfc64#diff-a1fcd115c3323774a21e53607d8ae5ca

**Comment by abonander** [comment]
@jyn514 these are already covered, I don't understand the problem. Is the returned type wrong for one of them?

**Comment by jyn514** [comment]
@kixiron do you remember why you special cased these?

**Comment by Kixiron** [comment]
It uses blanketed types instead of the exact ones, eg. `font` instead of `application/vnd.ms-fontobject` for `.eot`

**Comment by abonander** [comment]
Necroing this, but I can't actually find an original citation for `application/font-woff2` except some StackOverflow comments saying that it was the originally proposed Media Type. It's been `font/woff2` for years now.

Same thing for `ttf` and `application/x-font-ttf`. It was added to Wikipedia in December 2019 without a citation: https://en.wikipedia.org/w/index.php?title=TrueType&diff=prev&oldid=931818759

Is this actually necessary for browser compatibility?

**Comment by jyn514** [comment]
I have not looked too much into this. Removing the special casing on the docs.rs side seems fine to me if you think it's unnecessary.

**Comment by abonander** [comment]
I don't understand why it would be unless it was to support browsers that didn't recognize the new media types, but frankly that seems more like a docs.rs problem than a `mime_guess` problem.
