### ISSUE TITLE
Release a new version on crates.io

### ISSUE THREAD

**Issue by paolobarbolini** [abonander/mime_guess#68]
`tower-http` depends on `mime_guess` to obtain the correct `Content-Type` of the static files it serves.
`mime_guess` hasn't seen a release in the last year, meaning that new additions like bea27b3f487b9c4bbd01e5c6508cf9e18c94616a or fixes like 6f536cc758b5d76c893dc18c1bdf7ff76735afcc stil haven't reached most dependents on this crate. Could you please publish a new release? @abonander

**Comment by svenstaro** [comment]
I would also very much appreciate a release containing https://github.com/abonander/mime_guess/pull/66.

**Comment by svenstaro** [comment]
@abonander ping

**Comment by abonander** [comment]
`2.0.4` published, sorry for the delay.
